### PR TITLE
WIP bash autocomplete

### PR DESCRIPTION
**Pull request by ryanpitts**
Have the rc file for now, but currently requires you to fire off a `source elex.rc` each terminal session. Womp.

Currently researching how this should be added upon installation.

### CODE REVIEW

**Comment by ryanpitts** [comment]
The Django pattern seems to be to include the completion script in an `extras` directory, and provide instructions on testing and installing, then point to it from the docs.

https://docs.djangoproject.com/es/1.9/ref/django-admin/#bash-completion
https://github.com/django/django/blob/master/extras/django_bash_completion

**Comment by eads** [comment]
Oh, lovely. There's not a great way to install the bash completion scripts ... might be easier with a full blow package manager like apt-get or brew though.

**Comment by ryanpitts** [comment]
It looks to me like _maybe_ you can pass stuff like this into the `data_files` param on setup?

http://stackoverflow.com/questions/3127388/including-bash-autocompletion-with-setuptools

But that assumes that you've got an existing `/etc/bash_completion.d/`, which seems brittle. (I don't have that set up locally, for instance.)

**Comment by ryanpitts** [comment]
Oh ha, didn't realize this would get merged yet! I think there's going to be a bug where the `extras/elex_bash_completion` file doesn't get installed on `pip install`, right? It's not included in `MANIFEST.in` and it's not listed in the `packages` param in setup. I admit to not being sure the right way to approach packaging here.

**Comment by eads** [comment]
Sorry, got a little too excited! Let's keep iterating on this.

**Pull request merged**
