### PR TITLE
A first draft of a trend report wrapper

### PR DESCRIPTION
**Pull request by palewire**
If you look in the ``api.trends`` module here you can find my rough outline of classes that can collect the AP's trend report on governors, the U.S. Senate and U.S. House.

I've tried to conform my code to your delegate report code as close as possible. I've also put in some basic tests as a start. 

Running the code in Python right now works a little something like this, which, again, is modeled on how I think you guys approached the other classes.

```python
from elex.api import *

gr = USGovernorTrendReport()
print [o.serialize() for o in gr.parties]

sr = USSenateTrendReport()
print [o.serialize() for o in sr.parties]

hr = USHouseTrendReport()
print [o.serialize() for o in hr.parties]
```

I'm eager for any criticism, ideas or other suggestions. I want to help get this feature in, but I didn't want to go too far down the rabbit hole without getting your input. Part of that process was skipping your local file caching step for the time being (which we can of course add in if you think it works here).

### CODE REVIEW

**Comment by palewire** [comment]
push

If there's anything I can do to push this along, please let me know.

**Comment by eads** [comment]
It seems perhaps we need a way to pass in a data file for tests to work properly (or perhaps we can skip these tests). Data file handling very clunky right now and probably won't be improved before the election. 

I should have a chance to review in more depth in the next few nights. Got your branch up last night and promptly fell asleep.

**Comment by palewire** [comment]
Okay great. How do you generate those test files for other things, like the delegates? Just dump out the API results?

**Comment by eads** [comment]
Closing, continued in #300. @palewire you now have commit privileges on the main elex repo, just make branches with ticket #s as prefixes e.g. 0352-stop-blocking-shine.

**Pull request closed without merging**
